// Alla texter på sajten, på alla språk.
// Sidorna har svensk text i HTML-koden. Elementen har data-t="nyckel",
// och sprak.js byter texten till valt språk med hjälp av listan nedan.
// Text inom [hakparenteser] är platshållare som ska bytas mot riktigt innehåll.

window.TEXTER = {
  sv: {
    "sajt.namn": "Gården Ekön",
    "sprak.val": "Välj språk",
    "meny.namn": "Meny",
    "meny.hem": "Hem",
    "meny.stugan": "Stugan",
    "meny.hitta": "Hitta hit",
    "meny.guide": "Guide",
    "meny.info": "Info",
    "sidfot.integritet": "Integritet",
    "sidfot.boka": "Bokning sker via",

    "hem.titel": "Gården Ekön – Välkommen",
    "hem.rubrik": "Välkommen till Gården Ekön",
    "hem.ingress": "Din guide till stugan i Forserum och allt som finns runt omkring.",
    "hem.boka": "Boka på Booking.com",
    "hem.boka.info": "Bokning, priser och lediga datum finns på Booking.com.",
    "hem.halsning": "Varmt välkommen hit! Vi heter Karin och Jonas och bor granne med stugan. Vi vill att du ska känna dig välkommen och hoppas att du kommer att trivas här. På den här webbplatsen hittar du allt du behöver, oavsett om du planerar din semester eller redan har bokat stugan.",
    "hem.genvag.guide": "Tips i närheten",
    "hem.genvag.guide.text": "Bad, natur, fika och utflykter på en karta.",
    "hem.genvag.hitta": "Hitta hit",
    "hem.genvag.hitta.text": "Adress, vägbeskrivning och parkering.",
    "hem.genvag.info": "Praktisk info",
    "hem.genvag.info.text": "Incheckning och vanliga frågor.",
    "hem.overrubrik": "Stuga på småländska höglandet",

    "stugan.titel": "Stugan – Gården Ekön",
    "stugan.rubrik": "Om stugan",
    "stugan.ingress": "En renoverad stuga på 44 m² i en lugn och naturskön miljö på småländska höglandet, utanför Forserum mellan Jönköping och Nässjö. Här har ni hela stugan för er själva. Den passar den lilla familjen som vill njuta några dagar på landet. På baksidan finns en naturträdgård med utemöbler och grill.",
    "stugan.faciliteter": "Faciliteter",
    "stugan.faciliteter.text": "Stugan har plats för högst 4 gäster.",
    "stugan.fak.1": "1 sovrum med en stor dubbelsäng",
    "stugan.fak.2": "Vardagsrum med kök, matplats, soffa och våningssäng",
    "stugan.fak.3": "Fullt utrustat kök med kylskåp och ugn",
    "stugan.fak.4": "Eget badrum med dusch",
    "stugan.fak.5": "Tv med svenska och tyska kanaler",
    "stugan.fak.6": "Uteplats med utemöbler och grill",
    "stugan.fak.7": "Gratis parkering vid stugan",
    "stugan.fak.8": "Babysäng (0–2 år) finns gratis. Extrasängar finns inte.",
    "stugan.bilder": "Bilder",
    "stugan.bild.framsida": "Stugan från framsidan, med grusgång och gärdesgård",
    "stugan.bild.entre": "Entrén med farstukvist och gammal trädörr",
    "stugan.bild.soffgrupp": "Vardagsrummet med soffa, fåtöljer och tv",
    "stugan.bild.kok": "Köket med spis, ugn, kylskåp och mikro",
    "stugan.bild.sovrum": "Sovrummet med dubbelsäng",
    "stugan.bild.vaningssang": "Matplatsen och våningssängen i vardagsrummet",
    "stugan.bild.toalett": "Badrummet med dusch och toalett",
    "stugan.bild.fika": "Fika vid köksbordet",
    "stugan.bild.fonster": "Utsikt mot ängen genom fönstret",
    "stugan.bild.fonster-2": "Utsikt mot skogen och grusvägen",
    "stugan.bild.ljus": "Levande ljus på soffbordet",
    "stugan.bild.oppna": "Tryck på en bild för att se den större.",
    "bildvisare.namn": "Bildvisare",
    "bildvisare.stang": "Stäng",
    "bildvisare.foregaende": "Föregående bild",
    "bildvisare.nasta": "Nästa bild",
    "stugan.boka": "Se lediga datum på Booking.com",

    "hitta.titel": "Hitta hit – Gården Ekön",
    "hitta.rubrik": "Hitta hit",
    "hitta.adress": "Adress",
    "hitta.oppna": "Öppna i kartappen",
    "hitta.bil": "Vägbeskrivning",
    "hitta.bil.malmo": "Från Malmö (cirka 3 tim)",
    "hitta.bil.malmo.text": "Kör E6 mot Helsingborg, sedan E4 mot Stockholm. Ta avfart 93 (Torsvik) mot Tenhult och sedan väg 31 mot Nässjö.",
    "hitta.bil.goteborg": "Från Göteborg (cirka 2 tim)",
    "hitta.bil.goteborg.text": "Kör väg 40 mot Jönköping, sedan E4 mot Stockholm. Ta avfart 98 (Ekhagen) och sedan väg 31 mot Nässjö.",
    "hitta.bil.stockholm": "Från Stockholm (cirka 3,5 tim)",
    "hitta.bil.stockholm.text": "Kör E4 mot Jönköping. Ta avfart 98 (Ekhagen) och sedan väg 31 mot Nässjö.",
    "hitta.bil.slut": "Lämna väg 31 mot Forserum/Malmbäck. Sväng höger mot Malmbäck och sedan direkt höger mot Ekön.",
    "hitta.parkering": "Parkering",
    "hitta.parkering.text": "Det finns två parkeringsplatser alldeles bredvid stugan.",
    "hitta.sista": "Sista biten",
    "hitta.sista.text": "De sista två kilometerna går på grusväg genom tät granskog. Håll ut, du är snart framme!",

    "guide.titel": "Guide – Gården Ekön",
    "guide.rubrik": "Tips i närheten",
    "guide.ingress": "Välj vad du är intresserad av. Kartan och listan visar samma platser.",
    "guide.exempelvarning": "Just nu visas bara påhittade exempelplatser för att testa kartan.",
    "guide.filter": "Filtrera efter intresse",
    "guide.alla": "Alla",
    "guide.lista": "Platser",
    "guide.antal": "{n} platser",
    "guide.antal.en": "1 plats",
    "guide.vag": "Vägbeskrivning",
    "guide.visa": "Visa på kartan",
    "guide.ilistan": "Visa info",
    "guide.mer": "Webbplats",
    "guide.avstand": "Avstånd",
    "guide.sasong": "Säsong",
    "guide.exempel": "Exempel – ej verifierad",
    "guide.overifierad": "Ej verifierad",
    "guide.stugan": "Gården Ekön (ungefärligt läge)",
    "guide.laddar": "Laddar platser …",
    "guide.fel": "Platserna kunde inte laddas. Om du öppnat sidan direkt från datorn behöver den visas via en webbserver.",
    "guide.tvafingrar": "Använd två fingrar för att flytta kartan",
    "guide.tom": "Inga platser i den här kategorin än.",

    "kat.natur": "Natur",
    "kat.bad": "Bad",
    "kat.barnfamiljer": "Barnfamiljer",
    "kat.mat-och-fika": "Mat och fika",
    "kat.regnvader": "Regnväder",
    "kat.sevardheter": "Sevärdheter",

    "info.titel": "Praktisk info – Gården Ekön",
    "info.rubrik": "Praktisk information",
    "info.ingress": "Här finns svar på det gäster brukar undra över.",
    "info.in": "Incheckning och utcheckning",
    "info.in.text": "Incheckning kl. 16.00–20.00. Meddela gärna i förväg när ni beräknar att komma. Utcheckning kl. 07.00–11.00.",
    "info.fragor": "Vanliga frågor",
    "info.f1": "Hur kommer jag in i stugan?",
    "info.f1.svar": "Nyckelkoder och liknande detaljer får du efter bokning.",
    "info.parkering": "Kan jag parkera vid stugan?",
    "info.parkering.svar": "Ja, det finns två parkeringsplatser alldeles bredvid stugan, kostnadsfritt.",
    "info.f2": "Vad ska jag ta med mig?",
    "info.f2.svar": "Lakan och handdukar ingår inte. Ta med egna, eller hyr på plats för 150 kr per person.",
    "info.f3": "Får man ha husdjur med sig?",
    "info.f3.svar": "Nej, husdjur är tyvärr inte tillåtna.",
    "info.babysang": "Finns det babysäng att låna?",
    "info.babysang.svar": "Ja, det finns en hopfällbar babysäng (0–2 år) som ni får låna, kostnadsfritt.",
    "info.extrasang": "Kan man ställa in extrasängar?",
    "info.extrasang.svar": "Nej. Det finns bara fyra sängplatser i stugan, och en hopfällbar babysäng (0–2 år).",
    "info.rok": "Är stugan rökfri?",
    "info.rok.svar": "Ja, det är inte tillåtet att röka i stugan.",
    "info.wifi": "Finns det wifi?",
    "info.wifi.svar": "Nej, det finns tyvärr inget wifi i stugan just nu.",
    "info.parabol": "Vilka tv-kanaler finns det?",
    "info.parabol.svar": "Det finns svenska marksända kanaler och tyska kanaler via parabol.",
    "info.grill": "Finns det grill?",
    "info.grill.svar": "Ja, det finns en grill på baksidan av stugan.",
    "info.mat": "Var kan jag handla mat?",
    "info.mat.svar": "Närmaste matbutik är Coop, Jönköpingsvägen 2, Forserum.",
    "info.f4": "Vad gör jag innan jag åker hem?",
    "info.f4.svar": "Lämna stugan i samma skick som när ni kom. Sortera soporna och släng dem i soptunnorna på andra sidan vägen. Hyrda lakan och handdukar kan ni lägga på golvet bredvid sängen eller i badrummet.",
    "info.kontakt": "Kontakt",
    "info.kontakt.text": "Vi som är värdar bor alldeles intill stugan, så det är bara att komma och knacka på om ni har frågor eller om något krånglar. Det går också bra att skriva till oss i Booking.com-appen.",

    "integritet.titel": "Integritet – Gården Ekön",
    "integritet.rubrik": "Integritet",
    "integritet.p1": "Den här sajten använder inga cookies och ingen spårning. Vi samlar inte in några uppgifter om dig.",
    "integritet.p2": "Ditt val av språk och sajtens sidor sparas bara i din egen webbläsare, så att sajten minns språket, laddar snabbare och fungerar även utan täckning.",
    "integritet.p3": "Kartan på guidesidan hämtar kartbilder från OpenStreetMap. Då ser OpenStreetMap din IP-adress, precis som när du besöker vilken webbplats som helst.",
    "integritet.p4": "Bokningsknappen leder till Booking.com, som har sina egna regler för personuppgifter."
  },

  en: {
    "sajt.namn": "Gården Ekön",
    "sprak.val": "Choose language",
    "meny.namn": "Menu",
    "meny.hem": "Home",
    "meny.stugan": "Cottage",
    "meny.hitta": "Getting here",
    "meny.guide": "Guide",
    "meny.info": "Info",
    "sidfot.integritet": "Privacy",
    "sidfot.boka": "Booking is handled by",

    "hem.titel": "Gården Ekön – Welcome",
    "hem.rubrik": "Welcome to Gården Ekön",
    "hem.ingress": "Your guide to the cottage in Forserum and everything around it.",
    "hem.boka": "Book on Booking.com",
    "hem.boka.info": "Booking, prices and available dates are on Booking.com.",
    "hem.halsning": "A warm welcome! We are Karin and Jonas, and we live next door to the cottage. We want you to feel welcome and hope you will enjoy your time here. On this website you will find everything you need, whether you are planning your holiday or have already booked the cottage.",
    "hem.genvag.guide": "Things to do nearby",
    "hem.genvag.guide.text": "Swimming, nature, cafés and day trips on a map.",
    "hem.genvag.hitta": "Getting here",
    "hem.genvag.hitta.text": "Address, directions and parking.",
    "hem.genvag.info": "Practical info",
    "hem.genvag.info.text": "Check-in and frequently asked questions.",
    "hem.overrubrik": "Cottage in the Småland highlands",

    "stugan.titel": "The cottage – Gården Ekön",
    "stugan.rubrik": "About the cottage",
    "stugan.ingress": "A renovated 44 m² cottage in quiet, beautiful countryside in the Småland highlands, outside Forserum between Jönköping and Nässjö. You have the whole cottage to yourselves. It suits a small family who wants to enjoy a few days in the countryside. Behind the house there is a natural garden with outdoor furniture and a barbecue.",
    "stugan.faciliteter": "Facilities",
    "stugan.faciliteter.text": "The cottage sleeps up to 4 guests.",
    "stugan.fak.1": "1 bedroom with a large double bed",
    "stugan.fak.2": "Living room with kitchen, dining area, sofa and bunk bed",
    "stugan.fak.3": "Fully equipped kitchen with fridge and oven",
    "stugan.fak.4": "Private bathroom with shower",
    "stugan.fak.5": "TV with Swedish and German channels",
    "stugan.fak.6": "Patio with outdoor furniture and barbecue",
    "stugan.fak.7": "Free parking at the cottage",
    "stugan.fak.8": "A cot (0–2 years) is available free of charge. No extra beds.",
    "stugan.bilder": "Photos",
    "stugan.bild.framsida": "The cottage from the front, with gravel path and wooden fence",
    "stugan.bild.entre": "The entrance with porch and old wooden door",
    "stugan.bild.soffgrupp": "The living room with sofa, armchairs and TV",
    "stugan.bild.kok": "The kitchen with stove, oven, fridge and microwave",
    "stugan.bild.sovrum": "The bedroom with double bed",
    "stugan.bild.vaningssang": "The dining area and bunk bed in the living room",
    "stugan.bild.toalett": "The bathroom with shower and toilet",
    "stugan.bild.fika": "Coffee and biscuits at the table",
    "stugan.bild.fonster": "View of the meadow through the window",
    "stugan.bild.fonster-2": "View of the forest and the gravel road",
    "stugan.bild.ljus": "Candles on the coffee table",
    "stugan.bild.oppna": "Tap a photo to see it larger.",
    "bildvisare.namn": "Photo viewer",
    "bildvisare.stang": "Close",
    "bildvisare.foregaende": "Previous photo",
    "bildvisare.nasta": "Next photo",
    "stugan.boka": "See available dates on Booking.com",

    "hitta.titel": "Getting here – Gården Ekön",
    "hitta.rubrik": "Getting here",
    "hitta.adress": "Address",
    "hitta.oppna": "Open in maps app",
    "hitta.bil": "Directions",
    "hitta.bil.malmo": "From Malmö (about 3 h)",
    "hitta.bil.malmo.text": "Follow E6 towards Helsingborg, then E4 towards Stockholm. Take exit 93 (Torsvik) towards Tenhult and then road 31 towards Nässjö.",
    "hitta.bil.goteborg": "From Gothenburg (about 2 h)",
    "hitta.bil.goteborg.text": "Follow road 40 towards Jönköping, then E4 towards Stockholm. Take exit 98 (Ekhagen) and then road 31 towards Nässjö.",
    "hitta.bil.stockholm": "From Stockholm (about 3.5 h)",
    "hitta.bil.stockholm.text": "Follow E4 towards Jönköping. Take exit 98 (Ekhagen) and then road 31 towards Nässjö.",
    "hitta.bil.slut": "Leave road 31 towards Forserum/Malmbäck. Turn right towards Malmbäck and then immediately right towards Ekön.",
    "hitta.parkering": "Parking",
    "hitta.parkering.text": "There are two parking spaces right next to the cottage.",
    "hitta.sista": "The last stretch",
    "hitta.sista.text": "The last two kilometres are on a gravel road through dense spruce forest. Hang in there, you are nearly there!",

    "guide.titel": "Guide – Gården Ekön",
    "guide.rubrik": "Things to do nearby",
    "guide.ingress": "Choose what you are interested in. The map and the list show the same places.",
    "guide.exempelvarning": "For now, only made-up example places are shown, to test the map.",
    "guide.filter": "Filter by interest",
    "guide.alla": "All",
    "guide.lista": "Places",
    "guide.antal": "{n} places",
    "guide.antal.en": "1 place",
    "guide.vag": "Directions",
    "guide.visa": "Show on map",
    "guide.ilistan": "Show info",
    "guide.mer": "Website",
    "guide.avstand": "Distance",
    "guide.sasong": "Season",
    "guide.exempel": "Example – not verified",
    "guide.overifierad": "Not verified",
    "guide.stugan": "Gården Ekön (approximate location)",
    "guide.laddar": "Loading places …",
    "guide.fel": "The places could not be loaded. If you opened the page directly from your computer, it needs to be served by a web server.",
    "guide.tvafingrar": "Use two fingers to move the map",
    "guide.tom": "No places in this category yet.",

    "kat.natur": "Nature",
    "kat.bad": "Swimming",
    "kat.barnfamiljer": "Families",
    "kat.mat-och-fika": "Food & coffee",
    "kat.regnvader": "Rainy day",
    "kat.sevardheter": "Sights",

    "info.titel": "Practical info – Gården Ekön",
    "info.rubrik": "Practical information",
    "info.ingress": "Answers to the things guests usually wonder about.",
    "info.in": "Check-in and check-out",
    "info.in.text": "Check-in 4 pm–8 pm. Please let us know in advance roughly when you will arrive. Check-out 7 am–11 am.",
    "info.fragor": "Frequently asked questions",
    "info.f1": "How do I get into the cottage?",
    "info.f1.svar": "Key codes and similar details are sent to you after booking.",
    "info.parkering": "Can I park at the cottage?",
    "info.parkering.svar": "Yes, there are two parking spaces right next to the cottage, free of charge.",
    "info.f2": "What should I bring?",
    "info.f2.svar": "Bed linen and towels are not included. Bring your own, or rent them on site for SEK 150 per person.",
    "info.f3": "Are pets allowed?",
    "info.f3.svar": "No, unfortunately pets are not allowed.",
    "info.babysang": "Is there a cot to borrow?",
    "info.babysang.svar": "Yes, there is a folding cot (0–2 years) that you can borrow free of charge.",
    "info.extrasang": "Can extra beds be added?",
    "info.extrasang.svar": "No. There are only four beds in the cottage, plus a folding cot (0–2 years).",
    "info.rok": "Is the cottage non-smoking?",
    "info.rok.svar": "Yes, smoking is not allowed in the cottage.",
    "info.wifi": "Is there wifi?",
    "info.wifi.svar": "No, unfortunately there is no wifi in the cottage at the moment.",
    "info.parabol": "Which TV channels are there?",
    "info.parabol.svar": "There are Swedish terrestrial channels, and German channels via satellite.",
    "info.grill": "Is there a barbecue?",
    "info.grill.svar": "Yes, there is a barbecue at the back of the cottage.",
    "info.mat": "Where can I buy groceries?",
    "info.mat.svar": "The nearest grocery shop is Coop, Jönköpingsvägen 2, Forserum.",
    "info.f4": "What should I do before leaving?",
    "info.f4.svar": "Please leave the cottage in the same condition as you found it. Sort your rubbish and put it in the bins on the other side of the road. Rented bed linen and towels can be left on the floor next to the bed or in the bathroom.",
    "info.kontakt": "Contact",
    "info.kontakt.text": "We, your hosts, live right next to the cottage, so just come and knock on our door if you have any questions or if something is not working. You are also welcome to message us in the Booking.com app.",

    "integritet.titel": "Privacy – Gården Ekön",
    "integritet.rubrik": "Privacy",
    "integritet.p1": "This site uses no cookies and no tracking. We do not collect any information about you.",
    "integritet.p2": "Your language choice and the site's pages are stored only in your own browser, so the site remembers your language, loads faster and works even without a signal.",
    "integritet.p3": "The map on the guide page loads map images from OpenStreetMap. OpenStreetMap then sees your IP address, just as when you visit any website.",
    "integritet.p4": "The booking button takes you to Booking.com, which has its own privacy rules."
  },

  de: {
    "sajt.namn": "Gården Ekön",
    "sprak.val": "Sprache wählen",
    "meny.namn": "Menü",
    "meny.hem": "Start",
    "meny.stugan": "Ferienhaus",
    "meny.hitta": "Anfahrt",
    "meny.guide": "Tipps",
    "meny.info": "Infos",
    "sidfot.integritet": "Datenschutz",
    "sidfot.boka": "Die Buchung erfolgt über",

    "hem.titel": "Gården Ekön – Willkommen",
    "hem.rubrik": "Willkommen auf Gården Ekön",
    "hem.ingress": "Ihr Wegweiser zum Ferienhaus in Forserum und zu allem, was es in der Umgebung gibt.",
    "hem.boka": "Auf Booking.com buchen",
    "hem.boka.info": "Buchung, Preise und freie Termine finden Sie auf Booking.com.",
    "hem.halsning": "Herzlich willkommen! Wir sind Karin und Jonas und wohnen direkt neben dem Ferienhaus. Sie sollen sich bei uns willkommen fühlen, und wir hoffen, dass Sie sich hier wohlfühlen. Auf dieser Website finden Sie alles, was Sie brauchen, ob Sie Ihren Urlaub gerade planen oder das Ferienhaus schon gebucht haben.",
    "hem.genvag.guide": "Tipps in der Nähe",
    "hem.genvag.guide.text": "Baden, Natur, Cafés und Ausflüge auf einer Karte.",
    "hem.genvag.hitta": "Anfahrt",
    "hem.genvag.hitta.text": "Adresse, Wegbeschreibung und Parken.",
    "hem.genvag.info": "Praktische Infos",
    "hem.genvag.info.text": "Check-in und häufige Fragen.",
    "hem.overrubrik": "Ferienhaus im småländischen Hochland",

    "stugan.titel": "Das Ferienhaus – Gården Ekön",
    "stugan.rubrik": "Über das Ferienhaus",
    "stugan.ingress": "Ein renoviertes Ferienhaus mit 44 m² in ruhiger, schöner Landschaft im småländischen Hochland, außerhalb von Forserum zwischen Jönköping und Nässjö. Sie haben das ganze Haus für sich. Es eignet sich für die kleine Familie, die ein paar Tage auf dem Land genießen möchte. Hinter dem Haus gibt es einen Naturgarten mit Gartenmöbeln und Grill.",
    "stugan.faciliteter": "Ausstattung",
    "stugan.faciliteter.text": "Das Haus bietet Platz für höchstens 4 Gäste.",
    "stugan.fak.1": "1 Schlafzimmer mit einem großen Doppelbett",
    "stugan.fak.2": "Wohnzimmer mit Küche, Essbereich, Sofa und Etagenbett",
    "stugan.fak.3": "Voll ausgestattete Küche mit Kühlschrank und Backofen",
    "stugan.fak.4": "Eigenes Bad mit Dusche",
    "stugan.fak.5": "Fernseher mit schwedischen und deutschen Sendern",
    "stugan.fak.6": "Terrasse mit Gartenmöbeln und Grill",
    "stugan.fak.7": "Kostenlose Parkplätze am Haus",
    "stugan.fak.8": "Ein Babybett (0–2 Jahre) steht kostenlos zur Verfügung. Keine Zustellbetten.",
    "stugan.bilder": "Bilder",
    "stugan.bild.framsida": "Das Haus von vorne, mit Kiesweg und Holzzaun",
    "stugan.bild.entre": "Der Eingang mit Vorbau und alter Holztür",
    "stugan.bild.soffgrupp": "Das Wohnzimmer mit Sofa, Sesseln und Fernseher",
    "stugan.bild.kok": "Die Küche mit Herd, Backofen, Kühlschrank und Mikrowelle",
    "stugan.bild.sovrum": "Das Schlafzimmer mit Doppelbett",
    "stugan.bild.vaningssang": "Essbereich und Etagenbett im Wohnzimmer",
    "stugan.bild.toalett": "Das Bad mit Dusche und WC",
    "stugan.bild.fika": "Kaffee und Gebäck am Tisch",
    "stugan.bild.fonster": "Blick auf die Wiese durch das Fenster",
    "stugan.bild.fonster-2": "Blick auf den Wald und den Schotterweg",
    "stugan.bild.ljus": "Kerzen auf dem Couchtisch",
    "stugan.bild.oppna": "Tippen Sie auf ein Bild, um es größer zu sehen.",
    "bildvisare.namn": "Bildbetrachter",
    "bildvisare.stang": "Schließen",
    "bildvisare.foregaende": "Vorheriges Bild",
    "bildvisare.nasta": "Nächstes Bild",
    "stugan.boka": "Freie Termine auf Booking.com ansehen",

    "hitta.titel": "Anfahrt – Gården Ekön",
    "hitta.rubrik": "Anfahrt",
    "hitta.adress": "Adresse",
    "hitta.oppna": "In der Karten-App öffnen",
    "hitta.bil": "Wegbeschreibung",
    "hitta.bil.malmo": "Ab Malmö (ca. 3 Std.)",
    "hitta.bil.malmo.text": "Fahren Sie auf der E6 Richtung Helsingborg, dann E4 Richtung Stockholm. Nehmen Sie die Ausfahrt 93 (Torsvik) Richtung Tenhult und dann die Straße 31 Richtung Nässjö.",
    "hitta.bil.goteborg": "Ab Göteborg (ca. 2 Std.)",
    "hitta.bil.goteborg.text": "Fahren Sie auf der Straße 40 Richtung Jönköping, dann E4 Richtung Stockholm. Nehmen Sie die Ausfahrt 98 (Ekhagen) und dann die Straße 31 Richtung Nässjö.",
    "hitta.bil.stockholm": "Ab Stockholm (ca. 3,5 Std.)",
    "hitta.bil.stockholm.text": "Fahren Sie auf der E4 Richtung Jönköping. Nehmen Sie die Ausfahrt 98 (Ekhagen) und dann die Straße 31 Richtung Nässjö.",
    "hitta.bil.slut": "Verlassen Sie die Straße 31 Richtung Forserum/Malmbäck. Biegen Sie rechts ab Richtung Malmbäck und dann sofort wieder rechts Richtung Ekön.",
    "hitta.parkering": "Parken",
    "hitta.parkering.text": "Direkt neben dem Ferienhaus gibt es zwei Parkplätze.",
    "hitta.sista": "Das letzte Stück",
    "hitta.sista.text": "Die letzten zwei Kilometer führen über eine Schotterstraße durch dichten Fichtenwald. Durchhalten, Sie sind gleich da!",

    "guide.titel": "Tipps – Gården Ekön",
    "guide.rubrik": "Tipps in der Nähe",
    "guide.ingress": "Wählen Sie, was Sie interessiert. Karte und Liste zeigen dieselben Orte.",
    "guide.exempelvarning": "Zurzeit werden nur erfundene Beispielorte angezeigt, um die Karte zu testen.",
    "guide.filter": "Nach Interesse filtern",
    "guide.alla": "Alle",
    "guide.lista": "Orte",
    "guide.antal": "{n} Orte",
    "guide.antal.en": "1 Ort",
    "guide.vag": "Route",
    "guide.visa": "Auf der Karte zeigen",
    "guide.ilistan": "Info anzeigen",
    "guide.mer": "Website",
    "guide.avstand": "Entfernung",
    "guide.sasong": "Saison",
    "guide.exempel": "Beispiel – nicht geprüft",
    "guide.overifierad": "Nicht geprüft",
    "guide.stugan": "Gården Ekön (ungefähre Lage)",
    "guide.laddar": "Orte werden geladen …",
    "guide.fel": "Die Orte konnten nicht geladen werden. Wenn Sie die Seite direkt vom Computer geöffnet haben, muss sie über einen Webserver angezeigt werden.",
    "guide.tvafingrar": "Verschieben Sie die Karte mit zwei Fingern",
    "guide.tom": "In dieser Kategorie gibt es noch keine Orte.",

    "kat.natur": "Natur",
    "kat.bad": "Baden",
    "kat.barnfamiljer": "Familien",
    "kat.mat-och-fika": "Essen & Kaffee",
    "kat.regnvader": "Regenwetter",
    "kat.sevardheter": "Sehenswürdigkeiten",

    "info.titel": "Praktische Infos – Gården Ekön",
    "info.rubrik": "Praktische Informationen",
    "info.ingress": "Antworten auf das, was Gäste häufig wissen möchten.",
    "info.in": "Check-in und Check-out",
    "info.in.text": "Check-in 16:00–20:00 Uhr. Bitte teilen Sie uns vorab mit, wann Sie ungefähr ankommen. Check-out 7:00–11:00 Uhr.",
    "info.fragor": "Häufige Fragen",
    "info.f1": "Wie komme ich ins Haus?",
    "info.f1.svar": "Schlüsselcodes und ähnliche Details erhalten Sie nach der Buchung.",
    "info.parkering": "Kann ich am Ferienhaus parken?",
    "info.parkering.svar": "Ja, direkt neben dem Ferienhaus gibt es zwei Parkplätze, kostenfrei.",
    "info.f2": "Was soll ich mitbringen?",
    "info.f2.svar": "Bettwäsche und Handtücher sind nicht inklusive. Bringen Sie eigene mit oder mieten Sie sie vor Ort für 150 SEK pro Person.",
    "info.f3": "Sind Haustiere erlaubt?",
    "info.f3.svar": "Nein, Haustiere sind leider nicht erlaubt.",
    "info.babysang": "Gibt es ein Babybett zum Ausleihen?",
    "info.babysang.svar": "Ja, es gibt ein zusammenklappbares Babybett (0–2 Jahre), das Sie ausleihen können, kostenfrei.",
    "info.extrasang": "Kann man Zusatzbetten aufstellen?",
    "info.extrasang.svar": "Nein. Im Ferienhaus gibt es nur vier Schlafplätze und ein zusammenklappbares Babybett (0–2 Jahre).",
    "info.rok": "Ist das Ferienhaus rauchfrei?",
    "info.rok.svar": "Ja, im Ferienhaus darf nicht geraucht werden.",
    "info.wifi": "Gibt es WLAN?",
    "info.wifi.svar": "Nein, im Ferienhaus gibt es derzeit leider kein WLAN.",
    "info.parabol": "Welche Fernsehsender gibt es?",
    "info.parabol.svar": "Es gibt schwedische Sender über Antenne und deutsche Sender über Satellit.",
    "info.grill": "Gibt es einen Grill?",
    "info.grill.svar": "Ja, hinter dem Ferienhaus steht ein Grill.",
    "info.mat": "Wo kann ich Lebensmittel einkaufen?",
    "info.mat.svar": "Der nächste Supermarkt ist Coop, Jönköpingsvägen 2, Forserum.",
    "info.f4": "Was ist vor der Abreise zu tun?",
    "info.f4.svar": "Bitte hinterlassen Sie das Ferienhaus so, wie Sie es vorgefunden haben. Trennen Sie den Müll und werfen Sie ihn in die Mülltonnen auf der anderen Straßenseite. Gemietete Bettwäsche und Handtücher können Sie neben dem Bett oder im Badezimmer auf den Boden legen.",
    "info.kontakt": "Kontakt",
    "info.kontakt.text": "Wir, Ihre Gastgeber, wohnen direkt neben dem Ferienhaus. Klopfen Sie einfach bei uns an, wenn Sie Fragen haben oder etwas nicht funktioniert. Sie können uns auch gerne über die Booking.com-App schreiben.",

    "integritet.titel": "Datenschutz – Gården Ekön",
    "integritet.rubrik": "Datenschutz",
    "integritet.p1": "Diese Website verwendet keine Cookies und kein Tracking. Wir erheben keine Daten über Sie.",
    "integritet.p2": "Ihre Sprachwahl und die Seiten der Website werden nur in Ihrem eigenen Browser gespeichert, damit die Website Ihre Sprache kennt, schneller lädt und auch ohne Empfang funktioniert.",
    "integritet.p3": "Die Karte auf der Tipps-Seite lädt Kartenbilder von OpenStreetMap. Dabei sieht OpenStreetMap Ihre IP-Adresse, wie beim Besuch jeder anderen Website.",
    "integritet.p4": "Die Buchungsschaltfläche führt zu Booking.com, wo eigene Datenschutzregeln gelten."
  },

  nl: {
    "sajt.namn": "Gården Ekön",
    "sprak.val": "Kies taal",
    "meny.namn": "Menu",
    "meny.hem": "Home",
    "meny.stugan": "Huisje",
    "meny.hitta": "Route",
    "meny.guide": "Tips",
    "meny.info": "Info",
    "sidfot.integritet": "Privacy",
    "sidfot.boka": "Boeken gaat via",

    "hem.titel": "Gården Ekön – Welkom",
    "hem.rubrik": "Welkom op Gården Ekön",
    "hem.ingress": "Uw gids voor het huisje in Forserum en alles wat er in de buurt te doen is.",
    "hem.boka": "Boek op Booking.com",
    "hem.boka.info": "Boeken, prijzen en beschikbare data vindt u op Booking.com.",
    "hem.halsning": "Van harte welkom! Wij zijn Karin en Jonas en wonen naast het huisje. We willen dat u zich welkom voelt en hopen dat u het hier naar uw zin zult hebben. Op deze website vindt u alles wat u nodig hebt, of u nu uw vakantie aan het plannen bent of het huisje al hebt geboekt.",
    "hem.genvag.guide": "Tips in de buurt",
    "hem.genvag.guide.text": "Zwemmen, natuur, koffie en uitstapjes op een kaart.",
    "hem.genvag.hitta": "Route",
    "hem.genvag.hitta.text": "Adres, routebeschrijving en parkeren.",
    "hem.genvag.info": "Praktische info",
    "hem.genvag.info.text": "Inchecken en veelgestelde vragen.",
    "hem.overrubrik": "Vakantiehuisje in de Smålandse hooglanden",

    "stugan.titel": "Het huisje – Gården Ekön",
    "stugan.rubrik": "Over het huisje",
    "stugan.ingress": "Een gerenoveerd huisje van 44 m² in een rustige, mooie omgeving in de Smålandse hooglanden, buiten Forserum tussen Jönköping en Nässjö. U hebt het hele huisje voor uzelf. Het is geschikt voor een klein gezin dat een paar dagen van het platteland wil genieten. Achter het huis ligt een natuurtuin met tuinmeubelen en een barbecue.",
    "stugan.faciliteter": "Voorzieningen",
    "stugan.faciliteter.text": "Het huisje biedt plaats aan maximaal 4 gasten.",
    "stugan.fak.1": "1 slaapkamer met een groot tweepersoonsbed",
    "stugan.fak.2": "Woonkamer met keuken, eethoek, bank en stapelbed",
    "stugan.fak.3": "Volledig ingerichte keuken met koelkast en oven",
    "stugan.fak.4": "Eigen badkamer met douche",
    "stugan.fak.5": "Tv met Zweedse en Duitse zenders",
    "stugan.fak.6": "Terras met tuinmeubelen en barbecue",
    "stugan.fak.7": "Gratis parkeren bij het huisje",
    "stugan.fak.8": "Een babybedje (0–2 jaar) is gratis beschikbaar. Geen extra bedden.",
    "stugan.bilder": "Foto's",
    "stugan.bild.framsida": "Het huisje van voren, met grindpad en houten hek",
    "stugan.bild.entre": "De ingang met veranda en oude houten deur",
    "stugan.bild.soffgrupp": "De woonkamer met bank, fauteuils en tv",
    "stugan.bild.kok": "De keuken met fornuis, oven, koelkast en magnetron",
    "stugan.bild.sovrum": "De slaapkamer met tweepersoonsbed",
    "stugan.bild.vaningssang": "De eethoek en het stapelbed in de woonkamer",
    "stugan.bild.toalett": "De badkamer met douche en toilet",
    "stugan.bild.fika": "Koffie en koekjes op tafel",
    "stugan.bild.fonster": "Uitzicht op de weide door het raam",
    "stugan.bild.fonster-2": "Uitzicht op het bos en de grindweg",
    "stugan.bild.ljus": "Kaarsen op de salontafel",
    "stugan.bild.oppna": "Tik op een foto om hem groter te zien.",
    "bildvisare.namn": "Fotoviewer",
    "bildvisare.stang": "Sluiten",
    "bildvisare.foregaende": "Vorige foto",
    "bildvisare.nasta": "Volgende foto",
    "stugan.boka": "Bekijk beschikbare data op Booking.com",

    "hitta.titel": "Route – Gården Ekön",
    "hitta.rubrik": "Route",
    "hitta.adress": "Adres",
    "hitta.oppna": "Openen in kaarten-app",
    "hitta.bil": "Routebeschrijving",
    "hitta.bil.malmo": "Vanuit Malmö (ca. 3 uur)",
    "hitta.bil.malmo.text": "Volg de E6 richting Helsingborg en daarna de E4 richting Stockholm. Neem afrit 93 (Torsvik) richting Tenhult en daarna weg 31 richting Nässjö.",
    "hitta.bil.goteborg": "Vanuit Göteborg (ca. 2 uur)",
    "hitta.bil.goteborg.text": "Volg weg 40 richting Jönköping en daarna de E4 richting Stockholm. Neem afrit 98 (Ekhagen) en daarna weg 31 richting Nässjö.",
    "hitta.bil.stockholm": "Vanuit Stockholm (ca. 3,5 uur)",
    "hitta.bil.stockholm.text": "Volg de E4 richting Jönköping. Neem afrit 98 (Ekhagen) en daarna weg 31 richting Nässjö.",
    "hitta.bil.slut": "Verlaat weg 31 richting Forserum/Malmbäck. Sla rechtsaf richting Malmbäck en daarna meteen weer rechtsaf richting Ekön.",
    "hitta.parkering": "Parkeren",
    "hitta.parkering.text": "Direct naast het huisje zijn twee parkeerplaatsen.",
    "hitta.sista": "Het laatste stuk",
    "hitta.sista.text": "De laatste twee kilometer gaan over een grindweg door dicht sparrenbos. Volhouden, u bent er bijna!",

    "guide.titel": "Tips – Gården Ekön",
    "guide.rubrik": "Tips in de buurt",
    "guide.ingress": "Kies waar u in geïnteresseerd bent. De kaart en de lijst tonen dezelfde plekken.",
    "guide.exempelvarning": "Op dit moment worden alleen verzonnen voorbeeldplekken getoond, om de kaart te testen.",
    "guide.filter": "Filter op interesse",
    "guide.alla": "Alle",
    "guide.lista": "Plekken",
    "guide.antal": "{n} plekken",
    "guide.antal.en": "1 plek",
    "guide.vag": "Route",
    "guide.visa": "Toon op kaart",
    "guide.ilistan": "Toon info",
    "guide.mer": "Website",
    "guide.avstand": "Afstand",
    "guide.sasong": "Seizoen",
    "guide.exempel": "Voorbeeld – niet gecontroleerd",
    "guide.overifierad": "Niet gecontroleerd",
    "guide.stugan": "Gården Ekön (bij benadering)",
    "guide.laddar": "Plekken worden geladen …",
    "guide.fel": "De plekken konden niet worden geladen. Als u de pagina rechtstreeks vanaf uw computer hebt geopend, moet deze via een webserver worden getoond.",
    "guide.tvafingrar": "Gebruik twee vingers om de kaart te verschuiven",
    "guide.tom": "Nog geen plekken in deze categorie.",

    "kat.natur": "Natuur",
    "kat.bad": "Zwemmen",
    "kat.barnfamiljer": "Gezinnen",
    "kat.mat-och-fika": "Eten & koffie",
    "kat.regnvader": "Regenweer",
    "kat.sevardheter": "Bezienswaardigheden",

    "info.titel": "Praktische info – Gården Ekön",
    "info.rubrik": "Praktische informatie",
    "info.ingress": "Antwoorden op de vragen die gasten meestal hebben.",
    "info.in": "Inchecken en uitchecken",
    "info.in.text": "Inchecken 16.00–20.00 uur. Laat ons vooraf weten hoe laat u ongeveer aankomt. Uitchecken 7.00–11.00 uur.",
    "info.fragor": "Veelgestelde vragen",
    "info.f1": "Hoe kom ik het huisje in?",
    "info.f1.svar": "Sleutelcodes en dergelijke ontvangt u na het boeken.",
    "info.parkering": "Kan ik bij het huisje parkeren?",
    "info.parkering.svar": "Ja, direct naast het huisje zijn twee gratis parkeerplaatsen.",
    "info.f2": "Wat moet ik meenemen?",
    "info.f2.svar": "Beddengoed en handdoeken zijn niet inbegrepen. Neem ze zelf mee of huur ze ter plaatse voor 150 SEK per persoon.",
    "info.f3": "Zijn huisdieren toegestaan?",
    "info.f3.svar": "Nee, huisdieren zijn helaas niet toegestaan.",
    "info.babysang": "Kan ik een babybedje lenen?",
    "info.babysang.svar": "Ja, er is een opvouwbaar babybedje (0–2 jaar) dat u gratis kunt lenen.",
    "info.extrasang": "Kunnen er extra bedden bij?",
    "info.extrasang.svar": "Nee. Er zijn maar vier slaapplaatsen in het huisje, plus een opvouwbaar babybedje (0–2 jaar).",
    "info.rok": "Is het huisje rookvrij?",
    "info.rok.svar": "Ja, roken is in het huisje niet toegestaan.",
    "info.wifi": "Is er wifi?",
    "info.wifi.svar": "Nee, er is op dit moment helaas geen wifi in het huisje.",
    "info.parabol": "Welke tv-zenders zijn er?",
    "info.parabol.svar": "Er zijn Zweedse zenders via de antenne en Duitse zenders via de satelliet.",
    "info.grill": "Is er een barbecue?",
    "info.grill.svar": "Ja, achter het huisje staat een barbecue.",
    "info.mat": "Waar kan ik boodschappen doen?",
    "info.mat.svar": "De dichtstbijzijnde supermarkt is Coop, Jönköpingsvägen 2, Forserum.",
    "info.f4": "Wat moet ik doen voordat ik vertrek?",
    "info.f4.svar": "Laat het huisje achter zoals u het aantrof. Scheid uw afval en gooi het in de containers aan de overkant van de weg. Gehuurd beddengoed en handdoeken kunt u naast het bed of in de badkamer op de grond leggen.",
    "info.kontakt": "Contact",
    "info.kontakt.text": "Wij, uw gastheer en gastvrouw, wonen direct naast het huisje. Klop dus gerust bij ons aan als u vragen hebt of als er iets niet werkt. U kunt ons ook een bericht sturen via de Booking.com-app.",

    "integritet.titel": "Privacy – Gården Ekön",
    "integritet.rubrik": "Privacy",
    "integritet.p1": "Deze website gebruikt geen cookies en geen tracking. We verzamelen geen gegevens over u.",
    "integritet.p2": "Uw taalkeuze en de pagina's van de website worden alleen in uw eigen browser opgeslagen, zodat de website uw taal onthoudt, sneller laadt en ook zonder bereik werkt.",
    "integritet.p3": "De kaart op de tipspagina laadt kaartafbeeldingen van OpenStreetMap. OpenStreetMap ziet daarbij uw IP-adres, net als bij het bezoeken van elke andere website.",
    "integritet.p4": "De boekknop brengt u naar Booking.com, dat zijn eigen privacyregels heeft."
  },

  da: {
    "sajt.namn": "Gården Ekön",
    "sprak.val": "Vælg sprog",
    "meny.namn": "Menu",
    "meny.hem": "Hjem",
    "meny.stugan": "Huset",
    "meny.hitta": "Find vej",
    "meny.guide": "Guide",
    "meny.info": "Info",
    "sidfot.integritet": "Privatliv",
    "sidfot.boka": "Booking sker via",

    "hem.titel": "Gården Ekön – Velkommen",
    "hem.rubrik": "Velkommen til Gården Ekön",
    "hem.ingress": "Din guide til huset i Forserum og alt det, der er i omegnen.",
    "hem.boka": "Book på Booking.com",
    "hem.boka.info": "Booking, priser og ledige datoer finder du på Booking.com.",
    "hem.halsning": "Hjertelig velkommen! Vi hedder Karin og Jonas og bor lige ved siden af huset. Vi vil gerne have, at du føler dig velkommen, og håber, at du vil trives her. På denne hjemmeside finder du alt, hvad du har brug for, uanset om du er ved at planlægge din ferie eller allerede har booket huset.",
    "hem.genvag.guide": "Tips i nærheden",
    "hem.genvag.guide.text": "Badning, natur, caféer og udflugter på et kort.",
    "hem.genvag.hitta": "Find vej",
    "hem.genvag.hitta.text": "Adresse, vejvisning og parkering.",
    "hem.genvag.info": "Praktisk info",
    "hem.genvag.info.text": "Indtjekning og ofte stillede spørgsmål.",
    "hem.overrubrik": "Sommerhus i det smålandske højland",

    "stugan.titel": "Huset – Gården Ekön",
    "stugan.rubrik": "Om huset",
    "stugan.ingress": "Et renoveret hus på 44 m² i rolige og smukke omgivelser i det smålandske højland, uden for Forserum mellem Jönköping og Nässjö. I har hele huset for jer selv. Det passer til den lille familie, der vil nyde et par dage på landet. Bag huset er der en naturhave med havemøbler og grill.",
    "stugan.faciliteter": "Faciliteter",
    "stugan.faciliteter.text": "Huset har plads til højst 4 gæster.",
    "stugan.fak.1": "1 soveværelse med en stor dobbeltseng",
    "stugan.fak.2": "Stue med køkken, spiseplads, sofa og køjeseng",
    "stugan.fak.3": "Fuldt udstyret køkken med køleskab og ovn",
    "stugan.fak.4": "Eget badeværelse med bruser",
    "stugan.fak.5": "Tv med svenske og tyske kanaler",
    "stugan.fak.6": "Terrasse med havemøbler og grill",
    "stugan.fak.7": "Gratis parkering ved huset",
    "stugan.fak.8": "En babyseng (0–2 år) kan lånes gratis. Der er ingen ekstra senge.",
    "stugan.bilder": "Billeder",
    "stugan.bild.framsida": "Huset set forfra, med grussti og træhegn",
    "stugan.bild.entre": "Indgangen med veranda og gammel trædør",
    "stugan.bild.soffgrupp": "Stuen med sofa, lænestole og tv",
    "stugan.bild.kok": "Køkkenet med komfur, ovn, køleskab og mikrobølgeovn",
    "stugan.bild.sovrum": "Soveværelset med dobbeltseng",
    "stugan.bild.vaningssang": "Spisepladsen og køjesengen i stuen",
    "stugan.bild.toalett": "Badeværelset med bruser og toilet",
    "stugan.bild.fika": "Kaffe og småkager på bordet",
    "stugan.bild.fonster": "Udsigt over engen gennem vinduet",
    "stugan.bild.fonster-2": "Udsigt over skoven og grusvejen",
    "stugan.bild.ljus": "Stearinlys på sofabordet",
    "stugan.bild.oppna": "Tryk på et billede for at se det større.",
    "bildvisare.namn": "Billedfremviser",
    "bildvisare.stang": "Luk",
    "bildvisare.foregaende": "Forrige billede",
    "bildvisare.nasta": "Næste billede",
    "stugan.boka": "Se ledige datoer på Booking.com",

    "hitta.titel": "Find vej – Gården Ekön",
    "hitta.rubrik": "Find vej",
    "hitta.adress": "Adresse",
    "hitta.oppna": "Åbn i kort-appen",
    "hitta.bil": "Vejvisning",
    "hitta.bil.malmo": "Fra Malmö (ca. 3 timer)",
    "hitta.bil.malmo.text": "Følg E6 mod Helsingborg og derefter E4 mod Stockholm. Tag afkørsel 93 (Torsvik) mod Tenhult og derefter vej 31 mod Nässjö.",
    "hitta.bil.goteborg": "Fra Göteborg (ca. 2 timer)",
    "hitta.bil.goteborg.text": "Følg vej 40 mod Jönköping og derefter E4 mod Stockholm. Tag afkørsel 98 (Ekhagen) og derefter vej 31 mod Nässjö.",
    "hitta.bil.stockholm": "Fra Stockholm (ca. 3,5 timer)",
    "hitta.bil.stockholm.text": "Følg E4 mod Jönköping. Tag afkørsel 98 (Ekhagen) og derefter vej 31 mod Nässjö.",
    "hitta.bil.slut": "Forlad vej 31 mod Forserum/Malmbäck. Drej til højre mod Malmbäck og derefter straks til højre igen mod Ekön.",
    "hitta.parkering": "Parkering",
    "hitta.parkering.text": "Der er to parkeringspladser lige ved siden af huset.",
    "hitta.sista": "Det sidste stykke",
    "hitta.sista.text": "De sidste to kilometer går ad en grusvej gennem tæt granskov. Hold ud, I er næsten fremme!",

    "guide.titel": "Guide – Gården Ekön",
    "guide.rubrik": "Tips i nærheden",
    "guide.ingress": "Vælg det, du er interesseret i. Kortet og listen viser de samme steder.",
    "guide.exempelvarning": "Lige nu vises kun opdigtede eksempelsteder, så kortet kan testes.",
    "guide.filter": "Filtrér efter interesse",
    "guide.alla": "Alle",
    "guide.lista": "Steder",
    "guide.antal": "{n} steder",
    "guide.antal.en": "1 sted",
    "guide.vag": "Rutevejledning",
    "guide.visa": "Vis på kort",
    "guide.ilistan": "Vis info",
    "guide.mer": "Hjemmeside",
    "guide.avstand": "Afstand",
    "guide.sasong": "Sæson",
    "guide.exempel": "Eksempel – ikke kontrolleret",
    "guide.overifierad": "Ikke kontrolleret",
    "guide.stugan": "Gården Ekön (omtrentlig placering)",
    "guide.laddar": "Indlæser steder …",
    "guide.fel": "Stederne kunne ikke indlæses. Hvis du har åbnet siden direkte fra din computer, skal den vises via en webserver.",
    "guide.tvafingrar": "Brug to fingre til at flytte kortet",
    "guide.tom": "Der er endnu ingen steder i denne kategori.",

    "kat.natur": "Natur",
    "kat.bad": "Badning",
    "kat.barnfamiljer": "Børnefamilier",
    "kat.mat-och-fika": "Mad & kaffe",
    "kat.regnvader": "Regnvejr",
    "kat.sevardheter": "Seværdigheder",

    "info.titel": "Praktisk info – Gården Ekön",
    "info.rubrik": "Praktisk information",
    "info.ingress": "Svar på det, gæster plejer at undre sig over.",
    "info.in": "Indtjekning og udtjekning",
    "info.in.text": "Indtjekning kl. 16–20. Giv os gerne besked på forhånd om, hvornår I cirka kommer. Udtjekning kl. 7–11.",
    "info.fragor": "Ofte stillede spørgsmål",
    "info.f1": "Hvordan kommer jeg ind i huset?",
    "info.f1.svar": "Nøglekoder og lignende oplysninger får du efter bookingen.",
    "info.parkering": "Kan jeg parkere ved huset?",
    "info.parkering.svar": "Ja, der er to gratis parkeringspladser lige ved siden af huset.",
    "info.f2": "Hvad skal jeg have med?",
    "info.f2.svar": "Sengetøj og håndklæder er ikke inkluderet. Tag dit eget med, eller lej det på stedet for 150 SEK pr. person.",
    "info.f3": "Må man have kæledyr med?",
    "info.f3.svar": "Nej, kæledyr er desværre ikke tilladt.",
    "info.babysang": "Kan man låne en babyseng?",
    "info.babysang.svar": "Ja, der er en sammenklappelig babyseng (0–2 år), som I kan låne gratis.",
    "info.extrasang": "Kan der sættes ekstra senge ind?",
    "info.extrasang.svar": "Nej. Der er kun fire sovepladser i huset, plus en sammenklappelig babyseng (0–2 år).",
    "info.rok": "Er huset røgfrit?",
    "info.rok.svar": "Ja, rygning er ikke tilladt i huset.",
    "info.wifi": "Er der wifi?",
    "info.wifi.svar": "Nej, der er desværre ikke wifi i huset i øjeblikket.",
    "info.parabol": "Hvilke tv-kanaler er der?",
    "info.parabol.svar": "Der er svenske kanaler via antenne og tyske kanaler via satellit.",
    "info.grill": "Er der en grill?",
    "info.grill.svar": "Ja, der står en grill bag huset.",
    "info.mat": "Hvor kan jeg købe ind?",
    "info.mat.svar": "Den nærmeste dagligvarebutik er Coop, Jönköpingsvägen 2, Forserum.",
    "info.f4": "Hvad skal jeg gøre, før jeg rejser?",
    "info.f4.svar": "Efterlad venligst huset, som I fandt det. Sortér affaldet og læg det i affaldsspandene på den anden side af vejen. Lejet sengetøj og håndklæder kan lægges på gulvet ved sengen eller i badeværelset.",
    "info.kontakt": "Kontakt",
    "info.kontakt.text": "Vi, jeres værter, bor lige ved siden af huset, så bank bare på hos os, hvis I har spørgsmål, eller hvis noget ikke virker. I er også velkomne til at skrive til os i Booking.com-appen.",

    "integritet.titel": "Privatliv – Gården Ekön",
    "integritet.rubrik": "Privatliv",
    "integritet.p1": "Denne hjemmeside bruger ingen cookies og ingen sporing. Vi indsamler ingen oplysninger om dig.",
    "integritet.p2": "Dit sprogvalg og hjemmesidens sider gemmes kun i din egen browser, så hjemmesiden husker dit sprog, indlæses hurtigere og virker selv uden dækning.",
    "integritet.p3": "Kortet på guidesiden henter kortbilleder fra OpenStreetMap. OpenStreetMap ser derved din IP-adresse, ligesom når du besøger enhver anden hjemmeside.",
    "integritet.p4": "Bookingknappen fører dig til Booking.com, som har sine egne regler om privatliv."
  }
};
