// Alla texter på sajten, på alla språk.
// Sidorna har svensk text i HTML-koden. Elementen har data-t="nyckel",
// och sprak.js byter texten till valt språk med hjälp av listan nedan.
// Text inom [hakparenteser] är platshållare som ska bytas mot riktigt innehåll.

window.TEXTER = {
  sv: {
    "sajt.namn": "Gården Ekön",
    "sprak.val": "Välj språk",
    "meny.namn": "Meny",
    "meny.hem": "Hem",
    "meny.stugan": "Stugan",
    "meny.hitta": "Hitta hit",
    "meny.guide": "Guide",
    "meny.info": "Info",
    "sidfot.integritet": "Integritet",
    "sidfot.boka": "Bokning sker via Booking.com",

    "hem.titel": "Gården Ekön – välkommen",
    "hem.rubrik": "Välkommen till Gården Ekön",
    "hem.ingress": "Din guide till stugan i Forserum och allt som finns runt omkring.",
    "hem.boka": "Boka på Booking.com",
    "hem.boka.info": "Bokning, priser och lediga datum finns på Booking.com.",
    "hem.halsning": "[Platshållare: en kort, personlig hälsning från värden.]",
    "hem.genvag.guide": "Tips i närheten",
    "hem.genvag.guide.text": "Bad, natur, fika och utflykter på en karta.",
    "hem.genvag.hitta": "Hitta hit",
    "hem.genvag.hitta.text": "Adress, vägbeskrivning och parkering.",
    "hem.genvag.info": "Praktisk info",
    "hem.genvag.info.text": "Incheckning och vanliga frågor.",

    "stugan.titel": "Stugan – Gården Ekön",
    "stugan.rubrik": "Om stugan",
    "stugan.ingress": "[Platshållare: beskriv stugan och läget med några meningar.]",
    "stugan.faciliteter": "Faciliteter",
    "stugan.faciliteter.text": "[Platshållare: antal bäddar, kök, badrum med mera. Måste stämma med Booking.com.]",
    "stugan.bilder": "Bilder",
    "stugan.bild": "[Bild kommer]",
    "stugan.boka": "Se lediga datum på Booking.com",

    "hitta.titel": "Hitta hit – Gården Ekön",
    "hitta.rubrik": "Hitta hit",
    "hitta.adress": "Adress",
    "hitta.oppna": "Öppna i kartappen",
    "hitta.bil": "Med bil",
    "hitta.bil.text": "[Platshållare: vägbeskrivning med bil, till exempel från Nässjö eller Jönköping.]",
    "hitta.kollektivt": "Med kollektivtrafik",
    "hitta.kollektivt.text": "[Platshållare: närmaste tåg- eller busshållplats och hur man tar sig sista biten.]",
    "hitta.parkering": "Parkering",
    "hitta.parkering.text": "[Platshållare: var man parkerar.]",
    "hitta.sista": "Sista biten",
    "hitta.sista.text": "[Platshållare: kännetecken att hålla utkik efter, till exempel en brevlåda eller skylt.]",
    "hitta.koder": "Nyckelkoder och liknande detaljer får du efter bokning.",

    "guide.titel": "Guide – Gården Ekön",
    "guide.rubrik": "Tips i närheten",
    "guide.ingress": "Välj vad du är intresserad av. Kartan och listan visar samma platser.",
    "guide.exempelvarning": "Just nu visas bara påhittade exempelplatser för att testa kartan.",
    "guide.filter": "Filtrera efter intresse",
    "guide.alla": "Alla",
    "guide.lista": "Platser",
    "guide.antal": "{n} platser",
    "guide.antal.en": "1 plats",
    "guide.vag": "Vägbeskrivning",
    "guide.visa": "Visa på kartan",
    "guide.mer": "Mer information",
    "guide.avstand": "Avstånd",
    "guide.sasong": "Säsong",
    "guide.exempel": "Exempel – ej verifierad",
    "guide.stugan": "Gården Ekön (ungefärligt läge)",
    "guide.laddar": "Laddar platser …",
    "guide.fel": "Platserna kunde inte laddas. Om du öppnat sidan direkt från datorn behöver den visas via en webbserver.",
    "guide.tom": "Inga platser i den här kategorin än.",

    "kat.natur": "Natur",
    "kat.bad": "Bad",
    "kat.barnfamiljer": "Barnfamiljer",
    "kat.mat-och-fika": "Mat och fika",
    "kat.kultur": "Kultur",
    "kat.regnvader": "Regnväder",

    "info.titel": "Praktisk info – Gården Ekön",
    "info.rubrik": "Praktisk information",
    "info.ingress": "Här finns svar på det gäster brukar undra över.",
    "info.in": "Incheckning och utcheckning",
    "info.in.text": "[Platshållare: tider för in- och utcheckning. Måste stämma med Booking.com.]",
    "info.fragor": "Vanliga frågor",
    "info.f1": "Hur kommer jag in i stugan?",
    "info.f1.svar": "Nyckelkoder och liknande detaljer får du efter bokning.",
    "info.f2": "Vad ska jag ta med mig?",
    "info.f2.svar": "[Platshållare: till exempel lakan och handdukar, om de inte ingår.]",
    "info.f3": "Får man ha husdjur med sig?",
    "info.f3.svar": "[Platshållare: regler för husdjur. Måste stämma med Booking.com.]",
    "info.f4": "Vad gör jag innan jag åker hem?",
    "info.f4.svar": "[Platshållare: städning, sopor och annat inför avresa.]",
    "info.kontakt": "Kontakt",
    "info.kontakt.text": "[Platshållare: hur gästen når värden under vistelsen, till exempel via Booking.com.]",

    "integritet.titel": "Integritet – Gården Ekön",
    "integritet.rubrik": "Integritet",
    "integritet.p1": "Den här sajten använder inga cookies och ingen spårning. Vi samlar inte in några uppgifter om dig.",
    "integritet.p2": "Ditt val av språk sparas bara i din egen webbläsare, så att sajten minns det nästa gång.",
    "integritet.p3": "Kartan på guidesidan hämtar kartbilder från OpenStreetMap. Då ser OpenStreetMap din IP-adress, precis som när du besöker vilken webbplats som helst.",
    "integritet.p4": "Bokningsknappen leder till Booking.com, som har sina egna regler för personuppgifter."
  },

  en: {
    "sajt.namn": "Gården Ekön",
    "sprak.val": "Choose language",
    "meny.namn": "Menu",
    "meny.hem": "Home",
    "meny.stugan": "Cottage",
    "meny.hitta": "Getting here",
    "meny.guide": "Guide",
    "meny.info": "Info",
    "sidfot.integritet": "Privacy",
    "sidfot.boka": "Booking is handled by Booking.com",

    "hem.titel": "Gården Ekön – welcome",
    "hem.rubrik": "Welcome to Gården Ekön",
    "hem.ingress": "Your guide to the cottage in Forserum and everything around it.",
    "hem.boka": "Book on Booking.com",
    "hem.boka.info": "Booking, prices and available dates are on Booking.com.",
    "hem.halsning": "[Placeholder: a short, personal greeting from the host.]",
    "hem.genvag.guide": "Things to do nearby",
    "hem.genvag.guide.text": "Swimming, nature, cafés and day trips on a map.",
    "hem.genvag.hitta": "Getting here",
    "hem.genvag.hitta.text": "Address, directions and parking.",
    "hem.genvag.info": "Practical info",
    "hem.genvag.info.text": "Check-in and frequently asked questions.",

    "stugan.titel": "The cottage – Gården Ekön",
    "stugan.rubrik": "About the cottage",
    "stugan.ingress": "[Placeholder: describe the cottage and its surroundings in a few sentences.]",
    "stugan.faciliteter": "Facilities",
    "stugan.faciliteter.text": "[Placeholder: number of beds, kitchen, bathroom etc. Must match Booking.com.]",
    "stugan.bilder": "Photos",
    "stugan.bild": "[Photo coming]",
    "stugan.boka": "See available dates on Booking.com",

    "hitta.titel": "Getting here – Gården Ekön",
    "hitta.rubrik": "Getting here",
    "hitta.adress": "Address",
    "hitta.oppna": "Open in maps app",
    "hitta.bil": "By car",
    "hitta.bil.text": "[Placeholder: driving directions, for example from Nässjö or Jönköping.]",
    "hitta.kollektivt": "By public transport",
    "hitta.kollektivt.text": "[Placeholder: nearest train or bus stop and how to get the last stretch.]",
    "hitta.parkering": "Parking",
    "hitta.parkering.text": "[Placeholder: where to park.]",
    "hitta.sista": "The last stretch",
    "hitta.sista.text": "[Placeholder: landmarks to look out for, such as a mailbox or sign.]",
    "hitta.koder": "Key codes and similar details are sent to you after booking.",

    "guide.titel": "Guide – Gården Ekön",
    "guide.rubrik": "Things to do nearby",
    "guide.ingress": "Choose what you are interested in. The map and the list show the same places.",
    "guide.exempelvarning": "For now, only made-up example places are shown, to test the map.",
    "guide.filter": "Filter by interest",
    "guide.alla": "All",
    "guide.lista": "Places",
    "guide.antal": "{n} places",
    "guide.antal.en": "1 place",
    "guide.vag": "Directions",
    "guide.visa": "Show on map",
    "guide.mer": "More information",
    "guide.avstand": "Distance",
    "guide.sasong": "Season",
    "guide.exempel": "Example – not verified",
    "guide.stugan": "Gården Ekön (approximate location)",
    "guide.laddar": "Loading places …",
    "guide.fel": "The places could not be loaded. If you opened the page directly from your computer, it needs to be served by a web server.",
    "guide.tom": "No places in this category yet.",

    "kat.natur": "Nature",
    "kat.bad": "Swimming",
    "kat.barnfamiljer": "Families",
    "kat.mat-och-fika": "Food & coffee",
    "kat.kultur": "Culture",
    "kat.regnvader": "Rainy day",

    "info.titel": "Practical info – Gården Ekön",
    "info.rubrik": "Practical information",
    "info.ingress": "Answers to the things guests usually wonder about.",
    "info.in": "Check-in and check-out",
    "info.in.text": "[Placeholder: check-in and check-out times. Must match Booking.com.]",
    "info.fragor": "Frequently asked questions",
    "info.f1": "How do I get into the cottage?",
    "info.f1.svar": "Key codes and similar details are sent to you after booking.",
    "info.f2": "What should I bring?",
    "info.f2.svar": "[Placeholder: for example bed linen and towels, if not included.]",
    "info.f3": "Are pets allowed?",
    "info.f3.svar": "[Placeholder: pet rules. Must match Booking.com.]",
    "info.f4": "What should I do before leaving?",
    "info.f4.svar": "[Placeholder: cleaning, rubbish and other things before departure.]",
    "info.kontakt": "Contact",
    "info.kontakt.text": "[Placeholder: how guests reach the host during their stay, for example via Booking.com.]",

    "integritet.titel": "Privacy – Gården Ekön",
    "integritet.rubrik": "Privacy",
    "integritet.p1": "This site uses no cookies and no tracking. We do not collect any information about you.",
    "integritet.p2": "Your language choice is stored only in your own browser, so the site remembers it next time.",
    "integritet.p3": "The map on the guide page loads map images from OpenStreetMap. OpenStreetMap then sees your IP address, just as when you visit any website.",
    "integritet.p4": "The booking button takes you to Booking.com, which has its own privacy rules."
  },

  de: {
    "sajt.namn": "Gården Ekön",
    "sprak.val": "Sprache wählen",
    "meny.namn": "Menü",
    "meny.hem": "Start",
    "meny.stugan": "Ferienhaus",
    "meny.hitta": "Anfahrt",
    "meny.guide": "Tipps",
    "meny.info": "Infos",
    "sidfot.integritet": "Datenschutz",
    "sidfot.boka": "Die Buchung erfolgt über Booking.com",

    "hem.titel": "Gården Ekön – willkommen",
    "hem.rubrik": "Willkommen auf Gården Ekön",
    "hem.ingress": "Ihr Wegweiser zum Ferienhaus in Forserum und zu allem, was es in der Umgebung gibt.",
    "hem.boka": "Auf Booking.com buchen",
    "hem.boka.info": "Buchung, Preise und freie Termine finden Sie auf Booking.com.",
    "hem.halsning": "[Platzhalter: ein kurzer, persönlicher Gruß vom Gastgeber.]",
    "hem.genvag.guide": "Tipps in der Nähe",
    "hem.genvag.guide.text": "Baden, Natur, Cafés und Ausflüge auf einer Karte.",
    "hem.genvag.hitta": "Anfahrt",
    "hem.genvag.hitta.text": "Adresse, Wegbeschreibung und Parken.",
    "hem.genvag.info": "Praktische Infos",
    "hem.genvag.info.text": "Check-in und häufige Fragen.",

    "stugan.titel": "Das Ferienhaus – Gården Ekön",
    "stugan.rubrik": "Über das Ferienhaus",
    "stugan.ingress": "[Platzhalter: Beschreiben Sie das Haus und die Lage in einigen Sätzen.]",
    "stugan.faciliteter": "Ausstattung",
    "stugan.faciliteter.text": "[Platzhalter: Anzahl der Betten, Küche, Bad usw. Muss mit Booking.com übereinstimmen.]",
    "stugan.bilder": "Bilder",
    "stugan.bild": "[Bild folgt]",
    "stugan.boka": "Freie Termine auf Booking.com ansehen",

    "hitta.titel": "Anfahrt – Gården Ekön",
    "hitta.rubrik": "Anfahrt",
    "hitta.adress": "Adresse",
    "hitta.oppna": "In der Karten-App öffnen",
    "hitta.bil": "Mit dem Auto",
    "hitta.bil.text": "[Platzhalter: Wegbeschreibung mit dem Auto, zum Beispiel ab Nässjö oder Jönköping.]",
    "hitta.kollektivt": "Mit öffentlichen Verkehrsmitteln",
    "hitta.kollektivt.text": "[Platzhalter: nächster Bahnhof oder Bushaltestelle und wie man das letzte Stück zurücklegt.]",
    "hitta.parkering": "Parken",
    "hitta.parkering.text": "[Platzhalter: wo man parkt.]",
    "hitta.sista": "Das letzte Stück",
    "hitta.sista.text": "[Platzhalter: Erkennungszeichen, zum Beispiel ein Briefkasten oder ein Schild.]",
    "hitta.koder": "Schlüsselcodes und ähnliche Details erhalten Sie nach der Buchung.",

    "guide.titel": "Tipps – Gården Ekön",
    "guide.rubrik": "Tipps in der Nähe",
    "guide.ingress": "Wählen Sie, was Sie interessiert. Karte und Liste zeigen dieselben Orte.",
    "guide.exempelvarning": "Zurzeit werden nur erfundene Beispielorte angezeigt, um die Karte zu testen.",
    "guide.filter": "Nach Interesse filtern",
    "guide.alla": "Alle",
    "guide.lista": "Orte",
    "guide.antal": "{n} Orte",
    "guide.antal.en": "1 Ort",
    "guide.vag": "Route",
    "guide.visa": "Auf der Karte zeigen",
    "guide.mer": "Mehr Informationen",
    "guide.avstand": "Entfernung",
    "guide.sasong": "Saison",
    "guide.exempel": "Beispiel – nicht geprüft",
    "guide.stugan": "Gården Ekön (ungefähre Lage)",
    "guide.laddar": "Orte werden geladen …",
    "guide.fel": "Die Orte konnten nicht geladen werden. Wenn Sie die Seite direkt vom Computer geöffnet haben, muss sie über einen Webserver angezeigt werden.",
    "guide.tom": "In dieser Kategorie gibt es noch keine Orte.",

    "kat.natur": "Natur",
    "kat.bad": "Baden",
    "kat.barnfamiljer": "Familien",
    "kat.mat-och-fika": "Essen & Kaffee",
    "kat.kultur": "Kultur",
    "kat.regnvader": "Regenwetter",

    "info.titel": "Praktische Infos – Gården Ekön",
    "info.rubrik": "Praktische Informationen",
    "info.ingress": "Antworten auf das, was Gäste häufig wissen möchten.",
    "info.in": "Check-in und Check-out",
    "info.in.text": "[Platzhalter: Zeiten für Check-in und Check-out. Muss mit Booking.com übereinstimmen.]",
    "info.fragor": "Häufige Fragen",
    "info.f1": "Wie komme ich ins Haus?",
    "info.f1.svar": "Schlüsselcodes und ähnliche Details erhalten Sie nach der Buchung.",
    "info.f2": "Was soll ich mitbringen?",
    "info.f2.svar": "[Platzhalter: zum Beispiel Bettwäsche und Handtücher, falls nicht inklusive.]",
    "info.f3": "Sind Haustiere erlaubt?",
    "info.f3.svar": "[Platzhalter: Regeln für Haustiere. Muss mit Booking.com übereinstimmen.]",
    "info.f4": "Was ist vor der Abreise zu tun?",
    "info.f4.svar": "[Platzhalter: Reinigung, Müll und anderes vor der Abreise.]",
    "info.kontakt": "Kontakt",
    "info.kontakt.text": "[Platzhalter: wie Gäste den Gastgeber während des Aufenthalts erreichen, zum Beispiel über Booking.com.]",

    "integritet.titel": "Datenschutz – Gården Ekön",
    "integritet.rubrik": "Datenschutz",
    "integritet.p1": "Diese Website verwendet keine Cookies und kein Tracking. Wir erheben keine Daten über Sie.",
    "integritet.p2": "Ihre Sprachwahl wird nur in Ihrem eigenen Browser gespeichert, damit die Website sie beim nächsten Mal kennt.",
    "integritet.p3": "Die Karte auf der Tipps-Seite lädt Kartenbilder von OpenStreetMap. Dabei sieht OpenStreetMap Ihre IP-Adresse, wie beim Besuch jeder anderen Website.",
    "integritet.p4": "Die Buchungsschaltfläche führt zu Booking.com, wo eigene Datenschutzregeln gelten."
  }
};
